"""Add soft delete to customers

Revision ID: 69082619b844
Revises: 6c3be63faae2
Create Date: 2026-04-08 21:22:23.720399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69082619b844'
down_revision = '6c3be63faae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
